package com.github.muhsenerdev.genai.domain.prompt;

import com.github.muhsenerdev.commons.core.Assert;
import com.github.muhsenerdev.commons.core.InvalidDomainObjectException;

/**
 * Represents the type of output that can be generated by a prompt.
 */
public enum PromptOutputType {
    TEXT, IMAGE, AUDIO, VIDEO;

    /**
     * Converts a string value to the corresponding PromptOutputType enum.
     *
     * @param value the string value to convert (case-insensitive, trims whitespace)
     * @return the corresponding PromptOutputType
     * @throws InvalidDomainObjectException if the value does not match any enum
     *                                      constant
     */
    public static PromptOutputType of(String value) throws InvalidDomainObjectException {
        Assert.hasText(value, "value cannot be null or blank!");
        String normalizedValue = value.trim().toUpperCase();

        try {
            return valueOf(normalizedValue);
        } catch (IllegalArgumentException e) {
            throw new InvalidDomainObjectException("Unknown PromptOutputType: " + value, "prompt-output-type.unknown");
        }
    }
}
